# Generated by Django 3.2.4 on 2021-07-27 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0023_articlesviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('Жалоба на пользователя', 'Жалоба на пользователя'), ('Жалоба на статью', 'Жалоба на статью'), ('Жалоба на комментарий', 'Жалоба на комментарий')], db_index=True, max_length=50, verbose_name='Тип')),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена')], db_index=True, max_length=50, verbose_name='Статус')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('text_moderator', models.TextField(blank=True, verbose_name='Ответ модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='Статья')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.comment', verbose_name='Комментарий')),
                ('owner', models.ManyToManyField(related_name='usercomplaint', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
