# Generated by Django 3.2.4 on 2021-07-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_articlesviews'),
        ('notification', '0003_auto_20210720_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of',
            field=models.CharField(choices=[('Отклонено модератором!', 'Отклонено модератором!'), ('Лайк на статью', 'Лайк на статью'), ('Дизлайк на статью', 'Дизлайк на статью'), ('Новый комментарий', 'Новый комментарий'), ('Снято с публикации', 'Снято с публикации'), ('Комментарий удален', 'Комментарий удален'), ('Статья опубликована', 'Статья опубликована'), ('Cтатья восстановлена', 'Статья восстановлена'), ('Лайк на коммент', 'Лайк на коммент'), ('Дизлайк на коммент', 'Дизлайк на коммент'), ('Ответ на коммент', 'Ответ на коммент')], max_length=50, verbose_name='тип'),
        ),
    ]
