# Generated by Django 3.2.4 on 2021-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20210726_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of',
            field=models.CharField(choices=[('Отклонено модератором!', 'Отклонено модератором!'), ('Лайк на статью', 'Лайк на статью'), ('Дизлайк на статью', 'Дизлайк на статью'), ('Новый комментарий', 'Новый комментарий'), ('Снято с публикации', 'Снято с публикации'), ('Комментарий удален', 'Комментарий удален'), ('Статья опубликована', 'Статья опубликована'), ('Cтатья восстановлена', 'Статья восстановлена'), ('Лайк на коммент', 'Лайк на коммент'), ('Дизлайк на коммент', 'Дизлайк на коммент'), ('Ответ на коммент', 'Ответ на коммент'), ('Аккаунт заблокирован!', 'Аккаунт заблокирован!')], db_index=True, max_length=50, verbose_name='тип'),
        ),
    ]
