# Generated by Django 3.2.4 on 2021-07-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20210727_2303'),
        ('notification', '0006_auto_20210726_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint', verbose_name='Жалоба'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of',
            field=models.CharField(choices=[('Отклонено модератором!', 'Отклонено модератором!'), ('Лайк на статью', 'Лайк на статью'), ('Дизлайк на статью', 'Дизлайк на статью'), ('Новый комментарий', 'Новый комментарий'), ('Снято с публикации', 'Снято с публикации'), ('Комментарий удален', 'Комментарий удален'), ('Статья опубликована', 'Статья опубликована'), ('Cтатья восстановлена', 'Статья восстановлена'), ('Лайк на коммент', 'Лайк на коммент'), ('Дизлайк на коммент', 'Дизлайк на коммент'), ('Ответ на коммент', 'Ответ на коммент'), ('Аккаунт заблокирован!', 'Аккаунт заблокирован!'), ('Новая жалоба', 'Новая жалоба'), ('Жалоба принята', 'Жалоба принята'), ('Жалоба отклонена', 'Жалоба отклонена')], db_index=True, max_length=50, verbose_name='тип'),
        ),
    ]
