# Generated by Django 3.2.4 on 2021-08-06 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_articlesviews'),
        ('notification', '0008_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.comment', verbose_name='Комментарий'),
        ),
    ]
