# Generated by Django 3.2.4 on 2021-06-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tagline',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='article',
            field=models.CharField(blank=True, max_length=256, verbose_name='статьи'),
        ),
    ]
