# Generated by Django 3.2.4 on 2021-06-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210628_2226'),
        ('authapp', '0004_auto_20210629_0533'),
    ]

    operations = [
    ]
