# Generated by Django 3.2.4 on 2021-06-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_userprofile_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='article',
            field=models.TextField(blank=True, max_length=512, verbose_name='статья'),
        ),
    ]
