# Generated by Django 3.2.4 on 2021-07-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_remove_userprofile_article'),
        ('authapp', '0009_user_is_moderator'),
    ]

    operations = [
    ]
