# Generated by Django 3.2.4 on 2021-07-26 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20210726_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
