# Generated by Django 3.2.4 on 2021-07-26 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_user_blocked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
