# Generated by Django 2.2 on 2021-07-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210703_1603'),
        ('article', '0008_comment'),
    ]

    operations = [
    ]
