# Generated by Django 3.2.4 on 2021-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
