# Generated by Django 3.2.4 on 2021-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20210706_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубликована'),
        ),
    ]
