# Generated by Django 2.2 on 2021-07-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210705_0056'),
        ('article', '0009_auto_20210706_1246'),
    ]

    operations = [
    ]
