# Generated by Django 2.2 on 2021-07-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_merge_20210706_1450'),
        ('article', '0010_auto_20210708_1330'),
    ]

    operations = [
    ]
