# Generated by Django 3.2.4 on 2021-07-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20210711_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.comment')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.comment')),
            ],
            bases=('article.comment',),
        ),
    ]
