# Generated by Django 2.2 on 2021-07-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_commentoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_for_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='is_for_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
