# Generated by Django 3.2.4 on 2021-07-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_article_is_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='moderate_comment',
            field=models.TextField(blank=True, verbose_name='Замечания модератора'),
        ),
    ]
