# Generated by Django 3.2.4 on 2021-07-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20210713_2247'),
        ('article', '0021_article_moderate_comment'),
    ]

    operations = [
    ]
